// <auto-generated />
namespace XDPM_PHATHANHSACH.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DoiNULL_NXB_DL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DoiNULL_NXB_DL));
        
        string IMigrationMetadata.Id
        {
            get { return "201711091728109_DoiNULL_NXB_DL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
